### ISSUE TITLE
Weird error on incorrect login

### ISSUE THREAD

**Issue by 7kasper** [simplyGits/MagisterJS#114] opened 2019-02-06 19:20 UTC
To reproduce try the following code:
```javascript
login: async function(mAuth) {
    this.magister = await magister({
        school: {
            url: 'https://' + this.get('school') + '.magister.net'
        },
        username: this.get('username'),
        password: this.get('password'),
        authCode: mAuth
    });
    return this;
}
```
Which will give the the following error:
```
Unhandled rejection TypeError: Cannot read property 'split' of null
    at Magister.login (C:\Users\Kasper\git\magbot3\node_modules\magister.js\lib\magister.js:581:59)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Perhaps we can handle the response a bit better?

**Comment by Argetan** [comment] 2019-02-06 20:21
Are you sure the authentication code (`mAuth` in your case) is up to date? Around 5 hours ago an update was pushed to [`magisterjs-authcode`](https://github.com/simplyGits/magisterjs-authcode).

**Comment by 7kasper** [comment] 2019-02-06 20:32
Pretty sure yeah. When I enter the correct username / password it works a ok.

**Comment by Argetan** [comment] 2019-02-06 20:46
https://github.com/simplyGits/MagisterJS/blob/a8a4f05fdc8189d258f4fac7ca81dfeb5f43ea17/src/magister.js#L467-L469

https://github.com/simplyGits/MagisterJS/blob/a8a4f05fdc8189d258f4fac7ca81dfeb5f43ea17/src/magister.js#L483-L485

Assuming you are on the latest version it should actually tell you wether your username or password is incorrect. Looking at your error it appears that it's thrown by this code block:
https://github.com/simplyGits/MagisterJS/blob/a8a4f05fdc8189d258f4fac7ca81dfeb5f43ea17/src/magister.js#L456-L466

Since you are able to authenticate using a correct username and password combination, I'm going to assume something goes wrong in either the `sessionId` or the `returnUrl`. 

What you could do is enter a wrong password and correct username, if that throws the erorr with the message property `Invalid password` then it's "safe" to assume the `TypeError` is caused by an invalid username. In this case you can let your program act accordingly and display an error if neccesary. Of course that is till there is a bug fix for this issue.

**Comment by Argetan** [comment] 2019-02-08 07:40
I was unable to reproduce the bug using an invalid username/password. However, when I passed in an invalid school URL it threw the following error:
```
TypeError: Cannot read property 'split' of null
    at Magister.login (/Users/julian/Delta/node_modules/magister.js/lib/magister.js:581)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)
```
Which is the same one as you got.

**Comment by Sj3rd** [comment] 2019-02-08 07:46
Yep, since normally the getSchools function throws an error when an invalid school, but when you pass the schoolurl directly there is no further error handling, so in the split function it dies

**Closed** 2019-02-11 19:48 UTC
Labels: bug
